// Builds the standalone worksheet, index.html, from src/.
//
//   node scripts/build.mjs          write index.html
//   node scripts/build.mjs --check  exit with an error if index.html does not match src/
//
// esbuild bundles the page code, src/app/main.mjs and everything it imports (src/core included), into one
// self-contained script that the page runs inline. The bundle is not minified, so the shipped page stays readable.
import {readFileSync, writeFileSync} from 'node:fs';
import {fileURLToPath, pathToFileURL} from 'node:url';
import {buildSync} from 'esbuild';

const root = new URL('../', import.meta.url);
const read = path => readFileSync(new URL(path, root), 'utf8');

export const GENERATED_COMMENT = '<!-- Generated by scripts/build.mjs from src/. Do not edit this file directly. -->';

// Style sheets in cascade order: later rules win, so this order is part of the design.
const STYLES = [
  'tokens-and-themes',
  'base',
  'header',
  'components',
  'progress-bar',
  'sections-and-profile',
  'questions',
  'export-and-tools',
  'share-and-danger',
  'footer',
  'scrollbar-and-scroll-ring',
  'responsive'
].map(name => `src/styles/${name}.css`);

// The page code as one script, plus esbuild's metafile, which lists every module and what it imports.
export function bundleApp() {
  const result = buildSync({
    absWorkingDir: fileURLToPath(root),
    entryPoints: ['src/app/main.mjs'],
    bundle: true,
    format: 'iife',
    charset: 'utf8',
    legalComments: 'none',
    metafile: true,
    write: false,
    logLevel: 'silent'
  });
  if (result.warnings.length) throw Error('esbuild warnings:\n' + result.warnings.map(w => w.text).join('\n'));
  return {code: result.outputFiles[0].text, metafile: result.metafile};
}

// Style sheets in cascade order, one blank line between files.
export function styles() {
  return STYLES.map(read).join('\n');
}

export function buildPage() {
  const {code} = bundleApp();
  if (/<\/script/i.test(code)) throw Error('The page script contains </script, which would end the inline script.');
  const parts = {
    styles: styles().replace(/\n$/, ''),
    'initial-theme': read('src/initial-theme.js').replace(/\n$/, ''),
    logo: readFileSync(new URL('src/assets/logo.png', root)).toString('base64'),
    app: code
  };
  const expected = {styles: 1, 'initial-theme': 1, logo: 2, app: 1};
  const template = read('src/page.html');
  const found = {};
  for (const [, name] of template.matchAll(/\{\{([\w-]+)\}\}/g)) found[name] = (found[name] || 0) + 1;
  for (const name of new Set([...Object.keys(found), ...Object.keys(expected)])) {
    if (found[name] !== expected[name])
      throw Error(`src/page.html has ${found[name] || 0} {{${name}}} placeholders; expected ${expected[name] || 0}.`);
  }
  // One pass, so text inserted from src/ is never scanned for placeholders.
  const page = template.replace(/\{\{([\w-]+)\}\}/g, (_, name) => parts[name]);
  if (!page.startsWith('<!doctype html>\n')) throw Error('src/page.html must start with <!doctype html>.');
  return page.replace('<!doctype html>\n', `<!doctype html>\n${GENERATED_COMMENT}\n`);
}

function main() {
  const target = new URL('index.html', root);
  const next = buildPage();
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== next) {
      console.error('index.html does not match src/. Run npm run build.');
      process.exit(1);
    }
    console.log('index.html matches src/.');
  } else {
    writeFileSync(target, next);
    console.log('Wrote index.html.');
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
